/**
 * MedNexus AI Assistant — deterministic FAQ/navigation engine.
 *
 * Scope guard: this assistant provides APPLICATION guidance only. It never
 * diagnoses, prescribes, or gives medical advice. If AI_API_KEY is set, a
 * provider call can be added in callExternal(); without a key the
 * deterministic engine below answers, so the feature never fakes an API.
 */
const { config } = require('../config/env');

const DISCLAIMER =
  'AI assistant provides application guidance only and does not provide medical diagnosis or treatment advice.';

/** Intents -> canned answers with UI navigation targets. */
const INTENTS = [
  {
    id: 'book',
    patterns: ['book', 'appointment', 'schedule', 'slot', 'reschedule'],
    answer:
      'To book an appointment: open **Find Doctor** in the sidebar, choose a doctor, pick a date and an available slot, add a short reason, then confirm. You will see it under **Appointments** with status "Scheduled".',
    link: { label: 'Go to Find Doctor', to: '/patient/doctors' },
  },
  {
    id: 'cancel',
    patterns: ['cancel'],
    answer:
      'To cancel: open **Appointments**, find the upcoming appointment card, and press **Cancel appointment**. Cancellation is allowed while the status is Scheduled or Confirmed.',
    link: { label: 'Go to Appointments', to: '/patient/appointments' },
  },
  {
    id: 'history',
    patterns: ['history', 'previous', 'past'],
    answer:
      'Your past visits live in **Appointment History** in the sidebar — it lists Completed and Cancelled appointments with their details.',
    link: { label: 'Go to Appointment History', to: '/patient/history' },
  },
  {
    id: 'records',
    patterns: ['record', 'prescription', 'diagnosis', 'report'],
    answer:
      'After a consultation, your doctor may add a medical record. You can read (but not edit) them under **Medical Records**. Records are access-controlled and every view is audited.',
    link: { label: 'Go to Medical Records', to: '/patient/records' },
  },
  {
    id: 'profile',
    patterns: ['profile', 'password', 'email', 'account'],
    answer:
      'Update your name, phone, date of birth or gender under **Profile**. Your role and patient ID are fixed for security, and password changes require your current password.',
    link: { label: 'Go to Profile', to: '/patient/profile' },
  },
  {
    id: 'doctor-consult',
    patterns: ['confirm', 'complete', 'consultation', 'medical record add'],
    answer:
      'Doctors: open **Today\'s Appointments** on your dashboard, pick an appointment, **Confirm** it, then use **Complete consultation** to add the medical record. Only your assigned patients are visible.',
    link: { label: 'Go to Dashboard', to: '/doctor' },
  },
  {
    id: 'doctor-patients',
    patterns: ['my patients', 'assigned', 'patient list'],
    answer:
      'Doctors see only patients linked to them by an appointment or a record they authored, under **Patients**. Unauthorized access attempts are blocked and audited.',
    link: { label: 'Go to Patients', to: '/doctor/patients' },
  },
  {
    id: 'admin-audit',
    patterns: ['audit', 'log', 'security log'],
    answer:
      'Admins can review every security-relevant event (logins, bookings, record views, admin changes) under **Audit Logs**, filterable by action, role and result.',
    link: { label: 'Go to Audit Logs', to: '/admin/audit' },
  },
  {
    id: 'admin-doctors',
    patterns: ['add doctor', 'manage doctor', 'deactivate'],
    answer:
      'Admins manage the clinic under **Doctors** (add/edit, availability, activate/deactivate) and **Patients** (search, activate/deactivate). All admin actions are audited.',
    link: { label: 'Go to Doctors', to: '/admin/doctors' },
  },
  {
    id: 'demo-data',
    patterns: ['synthetic', 'demo', 'fake', 'real data', 'privacy'],
    answer:
      'All MedNexus data is **synthetic demo data** — no real patients, doctors, or medical facts. Names, records and ratings are fictional and generated by the seed script.',
  },
  {
    id: 'status-meaning',
    patterns: ['status mean', 'what does scheduled', 'confirmed mean', 'completed mean'],
    answer:
      'Statuses: **Scheduled** = booked and awaiting confirmation; **Confirmed** = the doctor confirmed your visit; **Completed** = consultation finished; **Cancelled** = cancelled by patient, doctor, or admin.',
  },
  {
    id: 'medical-advice-refusal',
    patterns: ['diagnose', 'diagnosis advice', 'what medicine', 'treatment for', 'should i take', 'symptom'],
    answer:
      'I can\'t help with symptoms, diagnoses, or medicines — that\'s a job for your doctor. I can guide you through MedNexus: booking, records, appointments, or navigating the app.',
    link: { label: 'Book a doctor visit', to: '/patient/doctors' },
  },
];

const GREETING =
  'Hi! I\'m the MedNexus assistant. I can help you navigate the app — booking, cancelling, records, history, and admin features. What do you need?';

function score(text, patterns) {
  const lower = text.toLowerCase();
  let s = 0;
  patterns.forEach((p) => { if (lower.includes(p)) s += p.length; });
  return s;
}

/** Deterministic answer selection. */
function answerLocally(message) {
  let best = null;
  let bestScore = 0;
  INTENTS.forEach((intent) => {
    const s = score(message, intent.patterns);
    if (s > bestScore) { best = intent; bestScore = s; }
  });
  if (!best || bestScore === 0) {
    return {
      reply: GREETING,
      link: null,
      source: 'deterministic',
    };
  }
  return { reply: best.answer, link: best.link || null, source: 'deterministic' };
}

/** Optional external provider hook. Never called without a key. */
async function callExternal(_message) {
  // Intentionally unimplemented: no key => no external call. To add a
  // provider, keep the system prompt restricted to app navigation and
  // re-use the same refusal rules for medical topics.
  return null;
}

async function ask(message) {
  if (config.ai.apiKey) {
    const external = await callExternal(message);
    if (external) return { ...external, disclaimer: DISCLAIMER };
  }
  return { ...answerLocally(message), disclaimer: DISCLAIMER };
}

module.exports = { ask, DISCLAIMER };
